import { Message, HealthProfile } from '../types';

export const formatProfileSummary = (profile?: HealthProfile): string => {
  if (!profile || (!profile.age && !profile.gender && !profile.preExistingConditions)) {
    return 'None provided';
  }
  const parts: string[] = [];
  if (profile.age) parts.push(`Age: ${profile.age}`);
  if (profile.gender) parts.push(`Biological Sex/Gender: ${profile.gender}`);
  if (profile.preExistingConditions) parts.push(`Pre-Existing / Chronic Conditions: ${profile.preExistingConditions}`);
  return parts.join(' | ');
};

export const generatePlainTextReport = (
  messages: Message[],
  healthProfile?: HealthProfile,
  includeProfile: boolean = true
): string => {
  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const timeStr = new Date().toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });

  let report = `=================================================================\n`;
  report += `               MEDIGUIDE AI - SYMPTOM ANALYSIS REPORT             \n`;
  report += `=================================================================\n\n`;
  report += `Generated: ${dateStr} at ${timeStr}\n`;

  if (includeProfile) {
    report += `\n-----------------------------------------------------------------\n`;
    report += `PATIENT HEALTH PROFILE CONTEXT\n`;
    report += `-----------------------------------------------------------------\n`;
    report += `${formatProfileSummary(healthProfile)}\n`;
  }

  report += `\n-----------------------------------------------------------------\n`;
  report += `CONSULTATION & SYMPTOM LOG (${messages.length} messages)\n`;
  report += `-----------------------------------------------------------------\n\n`;

  messages.forEach((msg, idx) => {
    const roleLabel = msg.role === 'user' ? 'PATIENT' : 'MEDIGUIDE AI';
    const timestampStr = new Date(msg.timestamp).toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit',
    });

    report += `[#${idx + 1}] ${roleLabel} (${timestampStr}):\n`;
    report += `${msg.content}\n`;
    if (msg.attachments && msg.attachments.length > 0) {
      report += `[Attached Images: ${msg.attachments.length} image(s) provided]\n`;
    }
    report += `-----------------------------------------------------------------\n\n`;
  });

  report += `\n=================================================================\n`;
  report += `DISCLAIMER: MediGuide AI is an artificial intelligence application for\n`;
  report += `educational purposes only and does not replace professional medical advice,\n`;
  report += `diagnosis, or treatment. In medical emergencies, contact local emergency services.\n`;
  report += `=================================================================\n`;

  return report;
};

export const generateMarkdownReport = (
  messages: Message[],
  healthProfile?: HealthProfile,
  includeProfile: boolean = true
): string => {
  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let md = `# MediGuide AI - Symptom Analysis Report\n\n`;
  md += `**Date:** ${dateStr}  \n`;

  if (includeProfile && healthProfile) {
    md += `\n## Patient Health Context\n`;
    md += `- **Age:** ${healthProfile.age || 'Not specified'}\n`;
    md += `- **Gender/Sex:** ${healthProfile.gender || 'Not specified'}\n`;
    md += `- **Pre-Existing Conditions:** ${healthProfile.preExistingConditions || 'None specified'}\n`;
  }

  md += `\n## Consultation Summary\n\n`;

  messages.forEach((msg) => {
    const roleLabel = msg.role === 'user' ? '👤 **Patient**' : '🩺 **MediGuide AI**';
    const time = new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    md += `### ${roleLabel} *(${time})*\n\n${msg.content}\n\n`;
    if (msg.attachments && msg.attachments.length > 0) {
      md += `*Attached ${msg.attachments.length} visual assessment image(s).*\n\n`;
    }
    md += `---\n\n`;
  });

  md += `> **Medical Disclaimer:** This document is generated by an AI assistant for informational use only. Always consult a qualified physician or healthcare provider for medical advice.`;

  return md;
};

export const downloadFile = (filename: string, content: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const printMedicalReport = (messages: Message[], healthProfile?: HealthProfile, includeProfile: boolean = true) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const formattedMessages = messages
    .map((msg) => {
      const isUser = msg.role === 'user';
      const roleLabel = isUser ? 'Patient Query' : 'MediGuide AI Analysis';
      const timeStr = new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      const bgClass = isUser ? '#f1f5f9' : '#f0fdf4';
      const borderClass = isUser ? '#cbd5e1' : '#bbf7d0';

      return `
        <div style="background-color: ${bgClass}; border: 1px solid ${borderClass}; padding: 14px 18px; margin-bottom: 14px; border-radius: 8px;">
          <div style="display: flex; justify-space-between: space-between; margin-bottom: 8px; border-bottom: 1px solid rgba(0,0,0,0.06); padding-bottom: 4px;">
            <strong style="color: ${isUser ? '#334155' : '#0f766e'}; font-size: 14px;">${roleLabel}</strong>
            <span style="color: #64748b; font-size: 12px;">${timeStr}</span>
          </div>
          <div style="font-size: 13px; line-height: 1.6; color: #1e293b; whitespace: pre-wrap;">
            ${msg.content.replace(/\n/g, '<br/>')}
          </div>
          ${
            msg.attachments && msg.attachments.length > 0
              ? `<div style="margin-top: 8px; font-size: 11px; color: #64748b; font-style: italic;">[Included ${msg.attachments.length} attachment image(s)]</div>`
              : ''
          }
        </div>
      `;
    })
    .join('');

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>MediGuide AI - Symptom Report (${dateStr})</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 30px; color: #0f172a; max-width: 800px; margin: 0 auto; }
          .header { border-bottom: 2px solid #0d9488; padding-bottom: 15px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-start; }
          .title { font-size: 22px; font-weight: bold; color: #0d9488; margin: 0; }
          .subtitle { font-size: 12px; color: #64748b; margin-top: 4px; }
          .section-title { font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; font-weight: 700; color: #334155; margin-top: 20px; margin-bottom: 10px; }
          .profile-box { background: #f8fafc; border: 1px solid #e2e8f0; padding: 12px 16px; border-radius: 8px; font-size: 13px; margin-bottom: 20px; }
          .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #64748b; line-height: 1.4; text-align: center; }
          @media print {
            body { padding: 0; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="no-print" style="margin-bottom: 20px; text-align: right;">
          <button onclick="window.print()" style="background: #0d9488; color: white; border: none; padding: 10px 18px; border-radius: 6px; font-weight: 600; cursor: pointer;">
            🖨️ Print or Save as PDF
          </button>
        </div>

        <div class="header">
          <div>
            <h1 class="title">MediGuide AI</h1>
            <p class="subtitle">Symptom & Clinical Insights Summary</p>
          </div>
          <div style="text-align: right; font-size: 12px; color: #64748b;">
            <div><strong>Date:</strong> ${dateStr}</div>
          </div>
        </div>

        ${
          includeProfile && healthProfile
            ? `
          <div class="section-title">Patient Health Context</div>
          <div class="profile-box">
            <strong>Age:</strong> ${healthProfile.age || 'Not provided'} &nbsp;|&nbsp;
            <strong>Gender/Sex:</strong> ${healthProfile.gender || 'Not provided'} &nbsp;|&nbsp;
            <strong>Conditions:</strong> ${healthProfile.preExistingConditions || 'None specified'}
          </div>
        `
            : ''
        }

        <div class="section-title">Consultation Log</div>
        <div>
          ${formattedMessages}
        </div>

        <div class="footer">
          <p><strong>Notice to Healthcare Provider:</strong> This report was compiled from a conversation with MediGuide AI. The information contained herein is intended for reference and educational context only. It does not constitute formal medical diagnosis or treatment plan.</p>
        </div>

        <script>
          // Auto trigger print dialog after page loads
          window.onload = function() {
            setTimeout(function() {
              window.print();
            }, 500);
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
};
